@startuml
class PhotoGallerySaver {
    + <<override>> Key : string <<get>>
    + <<override>> Save() : JObject
    + <<override>> Load(data:JObject) : bool
}
BaseSaver <|-- PhotoGallerySaver
@enduml
