@startuml
class SettingsPopUp {
    + <<override>> Priority : int <<get>>
    + <<override>> Load() : void
    + <<override>> Destroy() : void
    + <<override>> Open(context:object) : void
    + <<override>> Close() : void
}
struct ResolutionItem {
    + W : int
    + H : int
}
WindowPanel <|-- SettingsPopUp
SettingsPopUp +-- ResolutionItem
@enduml
