@startuml
class DragbleUIElement {
    +  <<event>> Drag : Action<Vector2> 
    + OnDrag(eventData:PointerEventData) : void
}
MonoBehaviour <|-- DragbleUIElement
IDragHandler <|-- DragbleUIElement
@enduml
