@startuml
class PlayerMoveSystem {
    + IsSprinting : bool <<get>>
    + IsCrouching : bool <<get>>
    + IsMoving : bool <<get>>
    +  <<event>> OnStep : Action<float> 
}
MonoBehaviour <|-- PlayerMoveSystem
@enduml
