@startuml
class DisappearObjectSaver {
    + <<override>> Key : string <<get>>
    + <<override>> Save() : JObject
    + <<override>> Load(data:JObject) : bool
}
BaseSaver <|-- DisappearObjectSaver
@enduml
