@startuml
class DialogIDProvider <<static>> {
    + {static} GetAllNodeIds() : IEnumerable<ValueDropdownItem<string>>
    + {static} GetAllChoiceIds() : IEnumerable<ValueDropdownItem<string>>
}
@enduml
