@startuml
!include .\\Animations\BlinkingAnimation.puml
!include .\\App\AppManager.puml
!include .\\App\AudioManager.puml
!include .\\App\ClientSettings.puml
!include .\\App\DependencyContainer.puml
!include .\\App\GameTime.puml
!include .\\App\GraphicsManager.puml
!include .\\App\InputHandler.puml
!include .\\App\InputSystemActions.puml
!include .\\Editor\Anchor.puml
!include .\\Events\EventManager.puml
!include .\\Game\CameraController.puml
!include .\\Game\ColliderDetector.puml
!include .\\Game\GameManager.puml
!include .\\Game\Interactable.puml
!include .\\Game\PlayerMoveSystem.puml
!include .\\HealsBar\ScrollHealth.puml
!include .\\SlidePresenter\Presenter.puml
!include .\\UI\DragbleUIElement.puml
!include .\\UI\Switcher.puml
!include .\\UI\YesNoPopup.puml
!include .\\WindowSwitcher\WindowPanel.puml
!include .\\WindowSwitcher\WindowSwitcher.puml
!include .\\App\Constants\WindowConstants.puml
!include .\\App\ValueProvider\DialogIDProvider.puml
!include .\\Events\App\AppEvents.puml
!include .\\Events\Game\DialogEvent.puml
!include .\\Events\Game\GameEvent.puml
!include .\\Events\Preview\PreviewEvent.puml
!include .\\Events\UI\UIEvents.puml
!include .\\Game\Dialog\DialogNode.puml
!include .\\Game\Dialog\DialogSystem.puml
!include .\\Game\Dialog\DialogСhoice.puml
!include .\\Game\Dialog\NPCDialog.puml
!include .\\Game\Items\Item.puml
!include .\\Game\Items\ItemsLibrary.puml
!include .\\Game\Items\PhotoCamera.puml
!include .\\Game\Items\PickableItem.puml
!include .\\Game\Items\UsableItem.puml
!include .\\Game\NPC\PatrolNPC.puml
!include .\\Game\NPC\PatrolNPCChase.puml
!include .\\Game\NPC\PatrolNPCPatrol.puml
!include .\\Game\NPC\PatrolNPCSearch.puml
!include .\\Game\Player\Flashlight.puml
!include .\\Game\Player\Inventory.puml
!include .\\Game\Player\PhotoGallery.puml
!include .\\Game\Player\Player.puml
!include .\\Game\Preview\PreviewShower.puml
!include .\\Game\Save\BaseSaver.puml
!include .\\Game\Save\SaveSystem.puml
!include .\\Game\Save\Utils.puml
!include .\\Game\Triggers\SceneTriggers.puml
!include .\\Game\Triggers\Trigger.puml
!include .\\Windows\Dialog\DialogWindow.puml
!include .\\Windows\Dialog\DialogWindowChoice.puml
!include .\\Windows\Dialog\DialogWindowContext.puml
!include .\\Windows\MainMenu\MainMenuWindow.puml
!include .\\Windows\Save\SaveSlot.puml
!include .\\Windows\Save\SaveWindow.puml
!include .\\Windows\Save\SaveWindowContext.puml
!include .\\Windows\Settings\SettingsPopUp.puml
!include .\\Game\Dialog\DialogActions\IDialogAction.puml
!include .\\Game\Save\Dialog\NPCDialogSaver.puml
!include .\\Game\Save\Items\DisappearObjectSaver.puml
!include .\\Game\Save\PhotoGallery\PhotoGallerySaver.puml
!include .\\Game\Save\Player\PlayerSaver.puml
!include .\\Game\Save\Triggers\SceneTriggersSaver.puml
!include .\\Game\Triggers\Conditions\ICondition.puml
!include .\\Game\Triggers\Conditions\ItemPickedUp.puml
!include .\\Game\Triggers\Conditions\OnTriggerEnterCondition.puml
!include .\\Game\Triggers\Conditions\OrCondition.puml
!include .\\Game\Triggers\Events\EnableTriggerEvent.puml
!include .\\Game\Triggers\Events\InnerDialogueTriggerEvent.puml
!include .\\Game\Triggers\Events\ITriggerEvent.puml
!include .\\Game\Triggers\Events\LoadNextSceneTriggerEvent.puml
!include .\\Game\Triggers\Events\SetActiveObjectTriggerEvent.puml
!include .\\Windows\App\Loading\LoadingWindow.puml
!include .\\Windows\Game\Inventory\InventoryWindow.puml
!include .\\Windows\Game\Pause\PauseWindow.puml
!include .\\Windows\Game\PhotoGallery\Photo.puml
!include .\\Windows\Game\PhotoGallery\PhotoGalleryWindow.puml
!include .\\Windows\Game\PlayerGUI\PlayerGUI.puml
!include .\\Game\Triggers\Conditions\Dialog\DialogChoiceCondition.puml
!include .\\Game\Triggers\Events\Dialog\SetStartNode.puml
@enduml
